image: shermine237/flutter-sdk:3.19.2-firebase

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - flutter build apk

  artifacts:
    paths:
      - "build/app/outputs/apk/release/app-release.apk"
    expire_in: 1 day

deploy:
  stage: deploy
  dependencies:
    - build

  script:
    - firebase appdistribution:distribute "build/app/outputs/apk/release/app-release.apk" --app $FIREBASE_APP_ID --token $FIREBASE_TOKEN
