// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAT8_qeQ7zc4OxIxPwARfW-x3DtnqfCd8',
    appId: '1:991260882274:web:474ecc01bc856c6a01683b',
    messagingSenderId: '991260882274',
    projectId: 'atelier3-a059c',
    authDomain: 'atelier3-a059c.firebaseapp.com',
    storageBucket: 'atelier3-a059c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbH-vNbLEFbq65vBcJOLCd8KQqiA3zdgE',
    appId: '1:991260882274:android:97b3ee6e61e6676001683b',
    messagingSenderId: '991260882274',
    projectId: 'atelier3-a059c',
    storageBucket: 'atelier3-a059c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHYNUIpMXm_XSCKS1pLCn6786JzUdLqhs',
    appId: '1:991260882274:ios:5515992622a170a201683b',
    messagingSenderId: '991260882274',
    projectId: 'atelier3-a059c',
    storageBucket: 'atelier3-a059c.appspot.com',
    iosBundleId: 'com.example.namer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHYNUIpMXm_XSCKS1pLCn6786JzUdLqhs',
    appId: '1:991260882274:ios:d179eb8ce2da095801683b',
    messagingSenderId: '991260882274',
    projectId: 'atelier3-a059c',
    storageBucket: 'atelier3-a059c.appspot.com',
    iosBundleId: 'com.example.namer.RunnerTests',
  );
}
